### ISSUE TITLE
npm start development is stuck

### ISSUE THREAD

**Issue by jsandesha** [digifi-io/loan-origination-system#111]
The `npm start development` is stuck with the following repetitive logs,

```
Mongoose: mlmodels.find({ 'aws.status': 'pending' }, { sort: { createdat: -1 }, skip: 0, limit: 500, projection: {} })
Mongoose: mlmodels.find({ digifi_model_status: 'pending' }, { sort: { updatedat: 1 }, limit: 1, projection: {} })
Mongoose: mlmodels.find({ digifi_model_status: 'input_analysis' }, { projection: {} })
Mongoose: mlmodels.find({ digifi_model_status: 'score_analysis' }, { projection: {} })
Mongoose: mlmodels.find({ digifi_model_status: 'batch_analysis' }, { projection: {} })
Mongoose: mlmodels.find({ status: 'training' }, { projection: {} })
```
And the app crashes after a while

**Comment by jsandesha** [comment]
Also getting ```
{
  message: "Cannot find module 'periodicjs.ext.admin/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js',
  stack: "Error: Cannot find module 'periodicjs.ext.admin/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:923:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:1140:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:75:18)\n' +
    '    at EventEmitter.<anonymous> (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js:783:15)\n' +
    '    at EventEmitter.emit (events.js:326:22)\n' +
    '    at EventEmitter.emit (domain.js:486:12)\n' +
    '    at /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js'
  ]
}
2020-10-28T07:56:47.832Z - error:  
{
  message: "Cannot find module 'periodicjs.ext.dbseed/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js',
  stack: "Error: Cannot find module 'periodicjs.ext.dbseed/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:923:27)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:1140:19)\n' +
    '    at require (internal/modules/cjs/helpers.js:75:18)\n' +
    '    at EventEmitter.<anonymous> (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js:783:15)\n' +
    '    at EventEmitter.emit (events.js:326:22)\n' +
    '    at EventEmitter.emit (domain.js:486:12)\n' +
    '    at /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/node_modules/periodicjs/index.js',
    '/Users/sandeshaj/Documents/Bitbucket/loan-origination-system/index.js'
  ]
}
```

**Comment by barryloanstack** [comment]
@jsandesha what did you do to resolve this issue?
