### ISSUE TITLE
While installing we got an error?

### ISSUE THREAD

**Issue by teamavengers-lobby** [digifi-io/loan-origination-system#12]
> @digifi-los/reactapp@0.0.4 postinstall /root/loan-origination-system/node_modules/@digifi-los/reactapp
> cd ../../../ && periodicjs aex periodicjs.ext.reactapp && cp -R node_modules/@digifi-los/reactapp/public/ public/extensions/periodicjs.ext.reactapp

(node:5575) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Mongoose: extensions.ensureIndex({ name: 1 }, { unique: true, background: true })
Mongoose: changesets.ensureIndex({ createdat: 1 }, { background: true })
(node:5575) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: configurations.findOne({ filepath: 'content/config/process/runtime.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.ensureIndex({ 'parent_document.id': 1 }, { background: true })
Could not initialize Periodic
Error: A valid runtime environment is required
    at /root/loan-origination-system/node_modules/periodicjs/lib/init/runtime.js:96:19
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
Mongoose: changesets.ensureIndex({ 'parent_document.document_type': 1 }, { background: true })

**Comment by codhah92** [comment]
It seems that you were on the right track when cloning our repository. The error you were getting when running `npm start development` after cloning is expected when you do not have the proper database configurations. If you follow our documentation on database configuration setup [here](https://docs.digifi.io/docs/database-configuration), you should be able to make more progress in completing the installation process. We recommend going with the git clone setup route (Option 1) for now.

**Comment by teamavengers-lobby** [comment]
I have configured the database properly.

While executed 'npm start development' it runs properly but at a point,
![stcuk](https://user-images.githubusercontent.com/54123627/63583099-f1ec6800-c5b7-11e9-924b-c14dc97c954d.png)
 it stuck for so long.

**Comment by barryloanstack** [comment]
@teamavengers-lobby I'm getting the same issue.  Any resolution?
