### ISSUE TITLE
 Package Not found @digifi-los/ml-cart

### ISSUE THREAD

**Issue by ghost-arbiter** [digifi-io/loan-origination-system#3]
I cloned the repo and made sure all the requirements are in place, yet I still recieve this same error message: "Not found : @digifi-los/ml-cart"? Any suggestions?

**Comment by codhah92** [comment]
Hey thanks for opening this issue. Can you try installing again? It should be working now. The npm package name should be @digifi/ml-cart.

**Comment by ghost-arbiter** [comment]
I re-cloned it and it seemed to get past the previous error, but now it's throwing a new error: " error: Could not initialize Periodic
{ Error: Cannot find module 'worker_threads'" ?

**Comment by codhah92** [comment]
That's most likely related to your node version - If you refer to our documentation here, you can see that we require Node 11 or later: https://docs.digifi.io/docs/system-requirements. We'd recommend running it on 11.7.0 as that is what our current build is running. You do not need to re-clone (you can just run the npm i commands again)

**Comment by codhah92** [comment]
Closing this issue now - second issue is related to a node version discrepancy.

**Comment by ghost-arbiter** [comment]
Hi,
So I successfully switched to the correct versions of node and npm. However, when I build and run the code, I can successfully navigate to localhost:8786, but it shows me a sample app page with the following message: "[Periodic](https://github.com/repetere/periodicjs) is a library for rapidily develop database agnostic enterprise applications with express & node.js."

How can I verify that I installed it correctly? Also, how can I navigate to the home page to be able to create users and login?

Thank you

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
