### ISSUE TITLE
Install and Run Locally

### ISSUE THREAD

**Issue by ghost-arbiter** [digifi-io/loan-origination-system#4]
When I build and run the code, I can successfully navigate to localhost:8786, but it shows me a sample app page with the following message: "Periodic is a library for rapidily develop database agnostic enterprise applications with express & node.js." 

How can I verify that I installed it correctly? Also, how can I navigate to the home page to be able to create users and login?

Thank you

**Comment by cdkirkwood** [comment]
Hi, 
Can you please let us know what scripts you ran to "build and run the code." Also please check your terminal when you start the app and let us know if you see any errors. Thank you!

**Comment by ghost-arbiter** [comment]
Hi,

I cloned the loan-originiation-system git repo.
I ran the following commands:
sudo npm i
sudo npm i periodicjs.ext.passport --save
sudo npm i periodicjs.ext.oauth2server@10.5.21 --save
sudo npm start development

The output I'm seeing is:

2019-08-14T13:52:45.860Z - error:
{
  message: "Cannot find module 'periodicjs.ext.passport/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js',
  stack: "Error: Cannot find module 'periodicjs.ext.passport/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)\n' +
    '    at Module.Hook._require.Module.require (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/require-in-the-middle/index.js:51:27)\n' +
    '    at require (internal/modules/cjs/helpers.js:68:18)\n' +
    '    at EventEmitter.<anonymous> (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js:783:15)\n' +
    '    at EventEmitter.emit (events.js:208:15)\n' +
    '    at EventEmitter.emit (domain.js:476:20)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js'
  ]
}
2019-08-14T13:52:45.865Z - error:
{
  message: "Cannot find module 'periodicjs.ext.oauth2server/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js',
  stack: "Error: Cannot find module 'periodicjs.ext.oauth2server/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)\n' +
    '    at Module.Hook._require.Module.require (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/require-in-the-middle/index.js:51:27)\n' +
    '    at require (internal/modules/cjs/helpers.js:68:18)\n' +
    '    at EventEmitter.<anonymous> (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js:783:15)\n' +
    '    at EventEmitter.emit (events.js:208:15)\n' +
    '    at EventEmitter.emit (domain.js:476:20)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js'
  ]
}
2019-08-14T13:52:45.866Z - error:
{
  message: "Cannot find module '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/content/container/periodicjs.container.default/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js',
  stack: "Error: Cannot find module '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/content/container/periodicjs.container.default/resources/async_routers/index'\n" +
    'Require stack:\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js\n' +
    '- /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js\n' +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)\n' +
    '    at Module.Hook._require.Module.require (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/require-in-the-middle/index.js:51:27)\n' +
    '    at require (internal/modules/cjs/helpers.js:68:18)\n' +
    '    at EventEmitter.<anonymous> (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js:809:61)\n' +
    '    at EventEmitter.emit (events.js:208:15)\n' +
    '    at EventEmitter.emit (domain.js:476:20)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:173:19\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Proxy.emitConfigurationComplete (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:171:10)\n' +
    '    at Proxy.initializeServers (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/server.js:189:33)\n' +
    '    at /home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/index.js:79:18\n' +
    '    at series (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/series_generator.js:22:24)\n' +
    '    at series.next (<anonymous>)\n' +
    '    at iterate (/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/node_modules/promisie/utility/iterator.js:8:27)',
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/config.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/init/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodicClass.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/lib/periodic.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules/periodicjs/index.js',
    '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/index.js'
  ]
}
2019-08-14T13:52:45.871Z - verbose: http server listening on port 8786
2019-08-14T13:52:45.871Z - verbose: https server listening on port 8787
2019-08-14T13:52:45.884Z - verbose: Initialized Periodic in 3.41 seconds

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cdkirkwood** [comment]
Try running those scripts without sudo. So just:
`npm i && npm i periodicjs.ext.passport --save && npm i periodicjs.ext.oauth2server@10.5.21 --save`
followed by:
`npm start development`

**Comment by ghost-arbiter** [comment]
I am given permission errors for needing write access to
Error: EACCES: permission denied, access '/home/testman/Desktop/loan-origin-system/finalcode/loan-origination-system/node_modules'

This is a clean version of Ubuntu 18.04. I have installed mongodb and redis. I'm not sure why I'm running into these issues? I've been following the docs in great detail.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by codhah92** [comment]
Hey there - It seems that you have a permission error that you may be able to resolve by referring to the official npm documentation: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally. 

If the above doesn't work, you can try running the following commands in succession:

`sudo chown -R `whoami` ~/.npm`
`sudo chown -R `whoami` /usr/local/lib/node_modules`

Then try running `npm i && npm i periodicjs.ext.passport --save && npm i periodicjs.ext.oauth2server@10.5.21 --save`
and then: 
`npm start development`

Generally, you do not want to run `sudo` with `npm install` as it can lead to a multitude of issues.

"I strongly encourage you not to do package management with sudo! Packages can run arbitrary scripts, which makes sudoing a package manager command as safe as a chainsaw haircut. Sure, it’s fast and definitely going to cut through any obstacles, but you might actually want that obstacle to stay there."

**Comment by ghost-arbiter** [comment]
Is there a developer that I can work with to install the los system cleanly from scratch?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by codhah92** [comment]
Feel free to send us an email at support@digifi.io to arrange a call. Closing this ticket - npm permissioning issue

**Comment by tsx-barrytallis** [comment]
@ghost-arbiter were you ever able to get this up and running?

**Comment by user12344-del** [comment]
@ghost-arbiter @tsx-barrytallis Have you found any solution to this problem? 

```
  message: "Cannot find module '/home/Desktop/loan-origination-system/content/container/periodicjs.container.default/resources/async_routers/index'\n" +
    'Require stack:\n' +
```

I have tried almost everything still getting this error.
