### ISSUE TITLE
npm WARN deprecated under Ubuntu 19.04 x64 + NodeJS 12.12

### ISSUE THREAD

**Issue by ckc** [digifi-io/loan-origination-system#42]
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated babel-preset-es2017@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated json-2-csv@2.4.0: Please upgrade to the latest version 3.x.x module for improved functionality.
npm WARN deprecated superagent@3.8.2: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
npm WARN deprecated doc-path@1.3.1: Please upgrade to 2.0.0
npm WARN deprecated deeks@1.0.0: Please upgrade to 2.0.0 or later
npm WARN deprecated bcrypt-nodejs@0.0.3: bcrypt-nodejs is no longer actively maintained. Please use bcrypt or bcryptjs. See https://github.com/kelektiv/node.bcrypt.js/wiki/bcrypt-vs-brypt.js to learn more about these two options
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated gcloud@0.10.0: gcloud has been renamed to google-cloud. To get new features and bug fixes, you must use the new package.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated core-js@1.1.0: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sendgrid@1.9.2: Please see v6.X+ at https://www.npmjs.com/org/sendgrid
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated json3@3.2.6: Please use the native JSON object instead of JSON 3
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> @newrelic/native-metrics@2.4.0 install /root/loan-origination-system/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/root/loan-origination-system/node_modules/@newrelic/native-metrics/lib/pre-build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

> deasync@0.1.15 install /root/loan-origination-system/node_modules/deasync
> node ./build.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/root/loan-origination-system/node_modules/deasync/build.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN react-countup@3.0.3 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
npm WARN react-countup@4.2.2 requires a peer of react@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.0 requires a peer of react@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN rc-switch@1.9.0 requires a peer of react-dom@^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-beautiful-dnd@10.1.1 requires a peer of react@^16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN babel-core@7.0.0-bridge.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-dates@16.7.1 requires a peer of react@^0.14 || ^15.5.4 || ^16.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-dates@16.7.1 requires a peer of react-dom@^0.14 || ^15.5.4 || ^16.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN connect-sequelize@2.0.2 requires a peer of sequelize@^3.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@2.4.0 (node_modules/@newrelic/native-metrics):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@2.4.0 install: `node ./lib/pre-build.js install native_metrics`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.15 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deasync@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-20T06_09_39_934Z-debug.log

**Comment by ConnectGrid** [comment]
I'm seeing similar issues, too. I'm not a Node expert, and so far I've lost hours trying to get this installation up and running on two different systems (one macOS and one Ubuntu 18.04). I think these outdated dependencies might be a factor in the pain.

I noticed that the platform is built on PeriodicJS, which seems to have been abandoned (last release in 2014), and recently changed hands, but new owner is slow to provide updates. Overall, a bit worrying to be relying on an outdated framework, I think?

Hoping that the DigiFi team irons out the wrinkles to make installation as simple as the documentation suggests it should be.

**Comment by codhah92** [comment]
Hey @ConnectGrid and @ckc:

Currently we're working off of node 11 - we are aware that there are some new updates to node 12 that aren't breaking changes in our application, but do display a small set of warnings in our application based on the code inside of PeriodicJS. A fix to that should be out in the near future, but for now working off of node 11 will work best.

As for PeriodicJS, DigiFi is always looking for ways to improve our platform.  While we believe Periodic works quite well as is, we will make a note to review this in further detail.
