### ISSUE TITLE
Worker_threads module not found

### ISSUE THREAD

**Issue by Kharvok** [digifi-io/loan-origination-system#69]
When running "npm start development" I get:

2019-12-08T16:29:08.342Z - debug: Running in environment: development
2019-12-08T16:29:08.347Z - error: Could not initialize Periodic
{ Error: Cannot find module 'worker_threads'

2019-12-08T16:29:09.479Z - debug: Your version of Periodic[10.70.92] is up to date with the current version [10.70.92]

I get around this by "node --experimental-worker index.js"

This seems to get the worker_threads working by using the experimental flag, but I still cannot access the login page to the program. Developing locally.

Mongoose: extensions.ensureIndex({ name: 1 }, { unique: true, background: true })
Mongoose: changesets.ensureIndex({ createdat: 1 }, { background: true })
(node:51176) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Mongoose: configurations.findOne({ filepath: 'content/config/process/runtime.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.ensureIndex({ 'parent_document.id': 1 }, { background: true })
Mongoose: configurations.findOne({ _id: ObjectId("5de8519440ae0bb45cb5e6bd") }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.ensureIndex({ 'parent_document.document_type': 1 }, { background: true })
Mongoose: configurations.updateOne({ _id: ObjectId("5de8519440ae0bb45cb5e6bd") }, { '$set': { updatedat: new Date("Sun, 08 Dec 2019 16:30:47 GMT"), createdat: new Date("Thu, 05 Dec 2019 00:38:44 GMT"), config: { process: { runtime: 'development' } }, filepath: 'content/config/process/runtime.json', container: 'periodicjs.container.default' } }, {})
Mongoose: configurations.findOne({ _id: ObjectId("5de8519440ae0bb45cb5e6bd") }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: configurations.findOne({ filepath: 'content/config/environment/development.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
Mongoose: changesets.insertOne({ _id: ObjectId("5ded25372a307ec7e839885a"), parent_document: { id: ObjectId("5de8519440ae0bb45cb5e6bd") }, changeset: { updatedat: [ '2019-12-08T16:30:47.139Z', '2019-12-06T01:41:16.110Z' ] }, createdat: new Date("Sun, 08 Dec 2019 16:30:47 GMT"), __v: 0 }, { session: null })
Mongoose: extensions.find({ '$and': [ {} ] }, { sort: { periodic_type: 1, periodic_priority: 1 }, skip: 0, limit: 1000, projection: {} })
Mongoose: configurations.findOne({ filepath: 'content/config/container/periodicjs.container.default/development.json' }, { sort: { filepath: -1, createdat: -1 }, projection: {} })
2019-12-08T16:30:48.614Z - debug: Running in environment: development
2019-12-08T16:30:48.624Z - verbose: http server listening on port 8786
2019-12-08T16:30:48.625Z - verbose: https server listening on port 8787
2019-12-08T16:30:48.625Z - verbose: Initialized Periodic in 2.35 seconds
2019-12-08T16:30:48.790Z - debug: Your version of Periodic[10.70.92] is up to date with the current version [10.70.92]

**Comment by MarkWaldron** [comment]
@Kharvok - You can fix this by using Node version `11.7.0` or higher. Worker threads became available in version `10.5.0` but required the use of `experimental-worker` flag.

**Comment by Kharvok** [comment]
solved.
