### ISSUE TITLE
API Support in this repo?

### ISSUE THREAD

**Issue by ConnectGrid** [digifi-io/loan-origination-system#73]
I've searched high and low, but can't find the API endpoint handlers in this package codebase. Am I missing something, or are they excluded?

I'd love to contribute to this project, largely on the API support side of things. For example, there doesn't seem to be any support for Product CRUD operations in the API, at least according to the documentation.

_(I had a call with Doug Webb last week, but forgot to ask about the API setup for a local installation. Please advise on API support within this package.)_

**Comment by tk-nguyen** [comment]
I think you can get the API endpoints in the network tab of your browser when you use the Decision Engine or other modules. At least that's what I did. Just check the request to URLs with some kind of ID in it like `5e01d79ee86083100675c09c`

**Comment by codhah92** [comment]
Hey @ConnectGrid and @tk-nguyen:

If you are looking for our API documentation, you can find that here: https://docs.digifi.io/reference. This reference contains the endpoints that are currently available, the parameters required and sample request/response pairs that you should expect when hitting the endpoints.

If you're looking for the the api endpoints inside of the codebase, you can navigate to the routers folder at `content/container/decision-engine-service/routers` and you should be able to find the routes that match the endpoints provided in our API reference.

Hope that helps!
