### ISSUE TITLE
Installed, but only see Sample App page, Nginx is proxy

### ISSUE THREAD

**Issue by ConnectGrid** [digifi-io/loan-origination-system#74]
Finally got things working ... to a point.

The LOS is listening on port 8786 correctly, and I have Nginx set as a proxy (same as I do for php-fpm apps). Only the **Sample App** page is appearing when I access the domain that I mapped to the app.

I haven't seen anyone else mention having a proxy web server in front of the LOS. Has this ever been tested? Could that be why things are not working as expected?

**Comment by bvanderstarren** [comment]
Hello!  Thanks for the question.  Please refer to our documentation and FAQ, which includes a similar question.  "After installation, all I see is a page with the DigiFi logo?"

https://docs.digifi.io/docs/installation-deployment
