### ISSUE TITLE
Problem with data integrations

### ISSUE THREAD

**Issue by tk-nguyen** [digifi-io/loan-origination-system#79]
I'm having some issues with the data integration modules in Digifi. When I created a new decision strategy and add a data integration module, if I run the decision it will hang the platform completely. It will not response to any request and I have to restart the node app for it to work again. But if I change an existing strategy by adding the integration module, the decision runs properly. Is there something wrong with my configs? 

Also, the documentation is written with XML configs. If I use REST, how can I change the document (more specifically the inputs and outputs, and the default configuration)?

**Comment by bvanderstarren** [comment]
Hi tk-nguyen!  Thanks for posting.  There are a lot of potential reasons for this, and it's likely related to configuration.  I suggest checking our documentation here: https://docs.digifi.io/docs/integrating-data-sources.

If you need further support configuring the platform, please contact info@digifi.io to discuss our support packages.  Thank you!
