### ISSUE TITLE
New install registration issue

### ISSUE THREAD

**Issue by anteatersa** [digifi-io/loan-origination-system#85]
I have just installed Digifi for testing purposes when I go to the register screen, fill in details and hit register I get the following error message in logs:

level: 'error', msg: 'No callback function was given. uncaughtException'

The registration page then just sites their "working" and nothing is inserted in users or organizations collection.

**Comment by AhmedAlZabidi** [comment]
@anteatersa how did you resolve the issue?

**Comment by davidcp90** [comment]
any updates on these @anteatersa ?
