### ISSUE TITLE
Failing to load components

### ISSUE THREAD

**Issue by ashish92yadav** [digifi-io/loan-origination-system#87]
Hi,

I setup and installed everything as mentioned in the docs here - https://docs.digifi.io/docs/platform-installation
Still on running "npm start development" and navigating to the url in browser, I'm getting failed to load component error. On inspecting the console in chrome dev mode, I'm able to see some connection refused errors in socketio urls. Anything that I need to do differently?

I'm running Node 11.15.0 and npm 6.7.0 with Ubuntu 18.04 on an EC2 instance.

Thanks

**Comment by codhah92** [comment]
Hey @ashish92yadav , it might just be that you're navigating to the http url as opposed to the https url. Please try navigating to the https url. Thanks!

**Comment by ashish92yadav** [comment]
Thank you @codhah92, will try with this.

**Comment by ashish92yadav** [comment]
It worked with https. Thank you.

Now I'm stuck behind a log-in page. I just wanted to try this as a demo. I tried "Create Account" as well. Getting this error - 
> TypeError: Cannot read property 'pathname' of undefined

Is there any test user account with which one can try out the LOS?

**Comment by ashish92yadav** [comment]
I am able to reach to the log in page with https.

I tried creating the account as mentioned here - https://docs.digifi.io/docs/database-configuration.
There is "clientid" key in place of "client_id" in the configuration files. And there is no "client_secret" key in  the configuration files to replace _YOUR_REACTAPP_CLIENT_SECRET_.

I tried both with and without creating key "clientsecret" wherever "clientid" is there.
Still there is this error - 
> TypeError: Cannot read property 'pathname' of undefined

**Comment by codhah92** [comment]
Hey @ashish92yadav , I believe this may be a Redis issue. Do you have Redis running somewhere with the host/port/password set up in your configuration files?

**Comment by ashish92yadav** [comment]
Hey @codhah92 , yes I have redis running in a docker container with host/port with no password though.

**Comment by codhah92** [comment]
@ashish92yadav  No password should be fine, but I'm wondering if your configuration files are set up with the proper host/port.

**Comment by ashish92yadav** [comment]
No, I checked everything again. My host and port are correctly set. I even started the redis docker with a separate redis.conf file to bind with 127.0.0.1 and 6379. Even now the same error is coming up

**Comment by tundraerp** [comment]
I changed my Redis host to localhost to resolve this issue. Also make sure password key is blank ""

**Comment by ashish92yadav** [comment]
Hey @tundraerp running redis locally and using localhost in place of 127.0.0.1 worked. Thank you. :)

_YOUR_REDIS_HOST_ is mentioned to be left as 127.0.0.1 for localhost here - https://docs.digifi.io/docs/database-configuration. This didn't work. Should this be updated? Or am I missing something here?

**Comment by codhah92** [comment]
Thanks @ashish92yadav , closing the ticket now!
