### ISSUE TITLE
Login - Invalid OAuth2 Client

### ISSUE THREAD

**Issue by tundraerp** [digifi-io/loan-origination-system#88]
Are there any default login creds? I'm trying to login / create account etc. and I get: 
```
Invalid OAuth2 Client
```
I'm sure it's a configuration tweak but not sure where to start looking. Amazing piece of software BTW..

**Comment by codhah92** [comment]
Hey @tundraerp , I saw your configurations json file from #86 and I noticed that your "clientid" values are pointing to a value of "admin". These "clientid" values should actually be set to a hash value, which can be found in one of the configuration documents in your "clients" collection. The document you should be looking for in this case has a name of "reactapp" and should have been auto generated for you. You can use the following query to find it: db.getCollection('clients').find({ name: /reactapp/}). Inside of that document should be a client_id pointing to a hash value. You should replace all of the "clientid": "admin" values in your configuration documents with this hash value. Let me know if this helps!

**Comment by tundraerp** [comment]
perfect, I'll check out out...thx

**Comment by mikkushukla** [comment]
This is pre installation step or post installation?

**Comment by codhah92** [comment]
@mikkushukla  post installation - this is for when you're trying to create a new account in the system

**Comment by mikkushukla** [comment]
any one liner script ? that will do that.

**Comment by tundraerp** [comment]
> Hey @tundraerp , I saw your configurations json file from #86 and I noticed that your "clientid" values are pointing to a value of "admin". These "clientid" values should actually be set to a hash value, which can be found in one of the configuration documents in your "clients" collection. The document you should be looking for in this case has a name of "reactapp" and should have been auto generated for you. You can use the following query to find it: db.getCollection('clients').find({ name: /reactapp/}). Inside of that document should be a client_id pointing to a hash value. You should replace all of the "clientid": "admin" values in your configuration documents with this hash value. Let me know if this helps!

Worked perfect - also in my configuration file I had the wrong AWS AccountkeyID. I had my AWS secret key instead of my actual AWS accountID,
