### ISSUE TITLE
Login error - "Cannot read property 'use_req_user_jwt' of undefined"

### ISSUE THREAD

**Issue by johnmpotter** [digifi-io/loan-origination-system#9]
Hey there, thanks a lot for open sourcing this platform, i'm excited to dive into it! 

I've been working to get it up and running over the past few days. I've run into a few configuration issues that I managed to get past, but i just came across one which i'm not sure is due to my configuration or not.

After creating a new account, i'm not able to log in. I get the error `Cannot read property 'use_req_user_jwt' of undefined`. The error is occuring in the `validateUserForUnauthenticatedRequest` function of [periodicjs.ext.oauth2server](https://github.com/repetere/periodicjs.ext.oauth2server/blob/9499c0c2e43b0722cc8d9d1ec8f6fc306d4b257c/utilities/auth.js#L18) at the line `if (req.session.use_req_user_jwt && req.user) {`. This function is called by `getJWTtoken()`. 

It appears that the session is destroyed in `if (req.session) req.session.destroy();` and remains undefined when `validateUserForUnauthenticatedRequest` is called. If I remove `req.session.destroy()`, i am able to log in as expected. 

It looks like that line in periodicjs.ext.oauth2server was added in one of the last two releases. Setting "periodicjs.ext.oauth2server" explicitly to version "10.5.21" also solved it.

**Comment by codhah92** [comment]
Hey John,

Yes that's the expected functionality. Glad you have been able to get it running - we are also on periodicjs.ext.oauth2server version 10.5.21, and if you check out our documentation [here](https://docs.digifi.io), we do require the installation of that specific version. Thanks for posting the issue. I'll be closing this one now.

**Comment by johnmpotter** [comment]
Hey Cody, thanks for the quick response!

The way you have the version defined in your package.json is the issue: `^10.5.21` means any 10.x.x version. Anyone who runs `npm install` for the first time will get version "10.6.1" with the code that breaks log in (or if you ever run `npm update`).

**Comment by codhah92** [comment]
Agreed! We are aware of this issue, and so in the documentation, we specify developers to run `npm i && npm i periodicjs.ext.passport --save && npm i periodicjs.ext.oauth2server@10.5.21 --save` so that the latter command will override the version on the oauth2server.

I do agree that the package.json should have the periodicjs.ext.oauth2server to point to `10.5.21` specifically, though. We'll make that update in the next release (most likely tomorrow). Thanks for following up!

**Comment by saisk73** [comment]
{"message":"Cannot read property 'use_req_user_jwt' of undefined","stack":"TypeError: Cannot read property 'use_req_user_jwt' of undefined\n    at Promise (/var/www/digifi/node_modules/periodicjs.ext.oauth2server/utilities/auth.js:18:23)\n    at new Promise (<anonymous>)\n    at validateUserForUnauthenticatedRequest (/var/www/digifi/node_modules/periodicjs.ext.oauth2server/utilities/auth.js:15:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}

I get the same error with all the packages installed according to the docs.
I have followed all the steps but I couldn't find where should I exactly replace client_secret in  YOUR_REACTAPP_CLIENT_SECRET.
Can you please help me with this error?
