### ISSUE TITLE
npm run development stuck

### ISSUE THREAD

**Issue by heyharmon** [digifi-io/loan-origination-system#95]
Hi team,

Upon completing database setup (https://docs.digifi.io/docs/database-configuration) and running "npm run development" command line is stuck at this line:

`Mongoose: losapplications.ensureIndex({ random: 1 }, { sparse: true, background: true })`

I am running Node v11.10.0, NPM 5.6.0, SSL cert in place and Redis running. You can also see my "configurations" collection critical values here: https://share.getcloudapp.com/WnuNQd6b

Is there an issue with my "losapplications" index in Mongo?

Thank you so much!

**Comment by kewlcherry** [comment]
I bumped in to the same issue, any help would be much appreciated

**Comment by joshtarun** [comment]
Hi, i am stuck at the same problem. Would you have any suggestions or advice on how to fix it?

**Comment by barryloanstack** [comment]
@heyharmon Were you able to resolve this?
