### ISSUE TITLE
URGENT:Could not initialize Periodic

### ISSUE THREAD

**Issue by saisk73** [digifi-io/loan-origination-system#97]
After npm start development command I'm facing the following issues
I couldnot start the server

2020-04-11T23:43:39.732Z - error: Could not initialize Periodic
TypeError: Invalid Version: undefined
    at new SemVer (/var/www/html/node_modules/semver/semver.js:305:11)
    at compare (/var/www/html/node_modules/semver/semver.js:614:39)
    at Function.lt (/var/www/html/node_modules/semver/semver.js:648:10)
    at Proxy.checkExtensionDependencies (/var/www/html/node_modules/periodicjs/lib/init/config.js:731:14)
    at extensions.forEach.ext (/var/www/html/node_modules/periodicjs/lib/init/config.js:748:64)
    at Array.forEach (<anonymous>)
    at crud.ext.list.then.extensions (/var/www/html/node_modules/periodicjs/lib/init/config.js:748:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by davidcp90** [comment]
The same is happening to me , I have tried changing node versions 11, 12 , etc, change the DB_CONFIG to use the mongodb URL with all the different hosts, but nothing is working.
I am getting this on different versions of Linux (16.04, 18.04, 20.04) and Debian (9,10)
@saisk73 Did you manage to solve it?
Weird thing is that I have been able to run it on my local mac

**Comment by saisk73** [comment]
> The same is happening to me , I have tried changing node versions 11, 12 , etc, change the DB_CONFIG to use the mongodb URL with all the different hosts, but nothing is working.
> I am getting this on different versions of Linux (16.04, 18.04, 20.04) and Debian (9,10)
> @saisk73 Did you manage to solve it?
> Weird thing is that I have been able to run it on my local mac

**Comment by saisk73** [comment]
@davidcp90 nope I didn't solve it I have contacted the Digifi CEO but they were asking $5000 for custom deployment. So my client has decided to built a custom application. Didn't try to deploy the application again. Did you resolve this issue or get any solution.

**Comment by davidcp90** [comment]
@saisk73 Kind of. It seems like a problem initializing something in Mongo. I have a version running on a server, but I have to use the mongo atlas instance that I set for my local computer. But I didn't manage to connect from the server to a brand new instance.

**Comment by saisk73** [comment]
> @saisk73 Kind of. It seems like a problem initializing something in Mongo. I have a version running on a server, but I have to use the mongo atlas instance that I set for my local computer. But I didn't manage to connect from the server to a brand new instance.

It's fixed now I am able to deploy the application it's due to incorrect mongodb configuration

**Comment by saisk73** [comment]
Closing the issue

**Comment by user12344-del** [comment]
@saisk73 I am trying to connect it with my atlas cluster. I believe my db config is fine because some data has been added in configurations collection initially. I was wondering what did you write in the client id?
